export const MathQuestions = [
  {
    prompt: "What is 2 + 2?",
    optionA: "3",
    optionB: "4",
    optionC: "5",
    optionD: "6",
    answer: "optionB",
  },
  {
    prompt: "What is 10 / 2?",
    optionA: "2",
    optionB: "5",
    optionC: "10",
    optionD: "20",
    answer: "optionB",
  },
  {
    prompt: "What is the square root of 64?",
    optionA: "6",
    optionB: "7",
    optionC: "8",
    optionD: "9",
    answer: "optionC",
  },
  {
    prompt: "What is the square root of 64?",
    optionA: "6",
    optionB: "7",
    optionC: "8",
    optionD: "9",
    answer: "optionC",
  },
  {
    prompt: "What is the value of Pi (π) to two decimal places?",
    optionA: "3.12",
    optionB: "3.14",
    optionC: "3.15",
    optionD: "3.16",
    answer: "optionB",
  },
  {
    prompt: "What is 15% of 200?",
    optionA: "20",
    optionB: "25",
    optionC: "30",
    optionD: "35",
    answer: "optionC",
  },
  {
    prompt: "What is the sum of angles in a triangle?",
    optionA: "90°",
    optionB: "180°",
    optionC: "270°",
    optionD: "360°",
    answer: "optionB",
  },
  {
    prompt: "What is the smallest prime number?",
    optionA: "1",
    optionB: "2",
    optionC: "3",
    optionD: "4",
    answer: "optionB",
  },
  {
    prompt: "What is 12 multiplied by 8?",
    optionA: "84",
    optionB: "92",
    optionC: "96",
    optionD: "108",
    answer: "optionC",
  },
  {
    prompt: "What is 100 divided by 4?",
    optionA: "20",
    optionB: "25",
    optionC: "30",
    optionD: "35",
    answer: "optionB",
  },
  {
    prompt: "What is the perimeter of a square with a side length of 5 cm?",
    optionA: "20 cm",
    optionB: "25 cm",
    optionC: "30 cm",
    optionD: "15 cm",
    answer: "optionA",
  },
  {
    prompt:
      "What is the area of a rectangle with a length of 8 cm and width of 3 cm?",
    optionA: "24 cm²",
    optionB: "26 cm²",
    optionC: "28 cm²",
    optionD: "30 cm²",
    answer: "optionA",
  },
  {
    prompt: "What is 9 squared?",
    optionA: "72",
    optionB: "81",
    optionC: "90",
    optionD: "99",
    answer: "optionB",
  },
  {
    prompt: "What is the value of Pi (π) to two decimal places?",
    optionA: "3.12",
    optionB: "3.14",
    optionC: "3.15",
    optionD: "3.16",
    answer: "optionB",
  },
  {
    prompt: "What is 15% of 200?",
    optionA: "20",
    optionB: "25",
    optionC: "30",
    optionD: "35",
    answer: "optionC",
  },
  {
    prompt: "What is the sum of angles in a triangle?",
    optionA: "90°",
    optionB: "180°",
    optionC: "270°",
    optionD: "360°",
    answer: "optionB",
  },
  {
    prompt: "What is the smallest prime number?",
    optionA: "1",
    optionB: "2",
    optionC: "3",
    optionD: "4",
    answer: "optionB",
  },
  {
    prompt: "What is 12 multiplied by 8?",
    optionA: "84",
    optionB: "92",
    optionC: "96",
    optionD: "108",
    answer: "optionC",
  },
  {
    prompt: "What is 100 divided by 4?",
    optionA: "20",
    optionB: "25",
    optionC: "30",
    optionD: "35",
    answer: "optionB",
  },
  {
    prompt: "What is the perimeter of a square with a side length of 5 cm?",
    optionA: "20 cm",
    optionB: "25 cm",
    optionC: "30 cm",
    optionD: "15 cm",
    answer: "optionA",
  },
  {
    prompt:
      "What is the area of a rectangle with a length of 8 cm and width of 3 cm?",
    optionA: "24 cm²",
    optionB: "26 cm²",
    optionC: "28 cm²",
    optionD: "30 cm²",
    answer: "optionA",
  },
  {
    prompt: "What is 9 squared?",
    optionA: "72",
    optionB: "81",
    optionC: "90",
    optionD: "99",
    answer: "optionB",
  },
  {
    prompt: "What is 2 + 2?",
    optionA: "3",
    optionB: "4",
    optionC: "5",
    optionD: "6",
    answer: "optionB",
  },
  {
    prompt: "What is 10 / 2?",
    optionA: "2",
    optionB: "5",
    optionC: "10",
    optionD: "20",
    answer: "optionB",
  },
  {
    prompt: "What is the square root of 64?",
    optionA: "6",
    optionB: "7",
    optionC: "8",
    optionD: "9",
    answer: "optionC",
  },
  {
    prompt: "What is the square root of 64?",
    optionA: "6",
    optionB: "7",
    optionC: "8",
    optionD: "9",
    answer: "optionC",
  },
  {
    prompt: "What is the value of Pi (π) to two decimal places?",
    optionA: "3.12",
    optionB: "3.14",
    optionC: "3.15",
    optionD: "3.16",
    answer: "optionB",
  },
];
