export const ScienceQuestions = [
  {
    prompt: "What is the chemical symbol for water?",
    optionA: "H2O",
    optionB: "CO2",
    optionC: "O2",
    optionD: "H2",
    answer: "optionA",
  },
  {
    prompt: "What planet is known as the Red Planet?",
    optionA: "Earth",
    optionB: "Mars",
    optionC: "Jupiter",
    optionD: "Saturn",
    answer: "optionB",
  },
  {
    prompt: "What is the chemical symbol for water?",
    optionA: "H2O",
    optionB: "CO2",
    optionC: "O2",
    optionD: "H2",
    answer: "optionA",
  },
  {
    prompt: "What planet is known as the Red Planet?",
    optionA: "Earth",
    optionB: "Mars",
    optionC: "Jupiter",
    optionD: "Saturn",
    answer: "optionB",
  },
  {
    prompt: "What is the process of plants making food called?",
    optionA: "Respiration",
    optionB: "Photosynthesis",
    optionC: "Transpiration",
    optionD: "Digestion",
    answer: "optionB",
  },
  {
    prompt: "Which gas is most abundant in Earth's atmosphere?",
    optionA: "Oxygen",
    optionB: "Hydrogen",
    optionC: "Nitrogen",
    optionD: "Carbon Dioxide",
    answer: "optionC",
  },
  {
    prompt: "What is the boiling point of water at sea level?",
    optionA: "50°C",
    optionB: "100°C",
    optionC: "150°C",
    optionD: "200°C",
    answer: "optionB",
  },
  {
    prompt: "Which planet is the largest in our solar system?",
    optionA: "Mars",
    optionB: "Earth",
    optionC: "Jupiter",
    optionD: "Saturn",
    answer: "optionC",
  },
  {
    prompt: "What is the basic unit of life?",
    optionA: "Tissue",
    optionB: "Organ",
    optionC: "Cell",
    optionD: "Atom",
    answer: "optionC",
  },
  {
    prompt: "What is the hardest natural substance on Earth?",
    optionA: "Gold",
    optionB: "Iron",
    optionC: "Diamond",
    optionD: "Quartz",
    answer: "optionC",
  },
  {
    prompt: "What is the center of an atom called?",
    optionA: "Electron",
    optionB: "Proton",
    optionC: "Nucleus",
    optionD: "Neutron",
    answer: "optionC",
  },
  {
    prompt: "What organ is responsible for pumping blood through the body?",
    optionA: "Lungs",
    optionB: "Brain",
    optionC: "Heart",
    optionD: "Liver",
    answer: "optionC",
  },
];
